apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: node-api:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
