apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-api-ingress

spec:
  rules:
    - host: 35.186.251.133.nip.io
      http:
        paths:
          - path: /v1/
            pathType: Prefix
            backend:
              service:
                name: node-api
                port:
                  number: 80
