apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS items (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      age INTEGER NOT NULL,
      gender VARCHAR(10),
      contact_info TEXT
    );

    INSERT INTO items (name, age, gender, contact_info) VALUES
    ('Alice', 30, 'Female', 'alice@example.com'),
    ('Bob', 25, 'Male', 'bob@example.com'),
    ('Charlie', 28, NULL, NULL),
    ('Diana', 35, 'Female', 'diana@example.com'),
    ('Ethan', 40, 'Male', 'ethan@example.com');
