# This Object can be created without having this Yaml File as well
# CLI command can be used kubectl create secret generic db-secret .....

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzMTIz